### ISSUE TITLE
Files no longer added to list after file access problem

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/lyse#1]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/lyse/issues/1)) by Shaun Johnstone (Bitbucket: [shjohnst](https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/), GitHub: [shjohnst](https://github.com/shjohnst)).**

----------------------------------------
lyse appears to fail to read a .h5 file that it is adding to its list, after which new incoming files fail to be added to the list.
I can see them coming in in the terminal as Webserver requests, but then the usual "INFO LYSE.FileBox.incoming: adding some files" line never comes.

The traceback from the read fail is:

```
#!python

Traceback (most recent call last):
  File "C:\pythonlib\labscript_utils\excepthook\__init__.py", line 32, in run
    run_old(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.pyw", line 570, in incoming_buffer_loop
    self.add_files(filepaths, marked=True)
  File "main.pyw", line 690, in add_files
    row = get_dataframe_from_shot(filepath)
  File "C:\pythonlib\lyse\dataframe_utilities.py", line 165, in get_dataframe_from_shot
    nested_dict = get_nested_dict_from_shot(filepath)
  File "C:\pythonlib\lyse\dataframe_utilities.py", line 62, in get_nested_dict_from_shot
    with h5py.File(filepath,'r') as h5_file:
  File "C:\pythonlib\labscript_utils\h5_lock.py", line 42, in __init__
    _orig_init(self, name, mode, driver, libver, **kwds)
  File "C:\Python27\lib\site-packages\h5py\_hl\files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "C:\Python27\lib\site-packages\h5py\_hl\files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py\h5f.c:1745)
IOError: unable to open file (File accessability: Unable to open file)

```

This should fail more gracefully and allow lyse to continue operating rather than requiring a restart. As far as BLACS is concerned, everything is OK and lyse is accepting the files for analysis, so it doesn't even queue them up to send to lyse once it is restarted.

**Comment by philipstarkey** [comment]
I'm going to close this is it was partially fixed in 0c4fff8f3dac0bb7decfb2a3379f13da887263f2. Failure to read the file no longer crashes lyse. BLACS still won't know if a file is handled by lyse correctly, but I don't think it should in order to keep things decoupled. A warning is printed to the lyse terminal if a shot cannot be opened, which I think is sufficient.
